name: "CI"

on:
  push:
    branches:
    - 'master'
    - 'dev'
    tags:
    - v*
  pull_request:

jobs:
  python-lint:
    name: Python linter
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pip
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools python3-pip

    - name: Install pyflakes
      run: pip install pyflakes

    - name: Run pylint
      run: |
        export PATH=${HOME}/Library/Python/3.8/bin:${HOME}/Library/Python/3.9/bin:${HOME}/.local/bin:${PATH}
        pyflakes .

  publish-docker-image:
    name: Publish Docker image on Docker Hub
    needs: [python-lint]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.head_ref, 'container'))
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools python3-pip

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/fufluns

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Publish to Registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fufluns:latest,${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
